# Model Training

This notebook trains and evaluates multiple machine learning models for fraud detection using the engineered dataset. 
The workflow includes data preparation, experiment tracking with MLflow, model training, performance evaluation, and model selection. The best-performing model will be used in the explainability stage of the proposed Explainable AI (XAI) fraud detection framework.
# Logistic Regression
# Random Forest
# XGBoost
# Model Evaluation

In [4]:
%pip install lightgbm

Requirement already satisfied: lightgbm in c:\Users\Olami\OneDrive\Documents\DATASCIENCEPROJECT\.venv-1\Lib\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in c:\Users\Olami\OneDrive\Documents\DATASCIENCEPROJECT\.venv-1\Lib\site-packages (from lightgbm) (2.4.6)
Requirement already satisfied: scipy in c:\Users\Olami\OneDrive\Documents\DATASCIENCEPROJECT\.venv-1\Lib\site-packages (from lightgbm) (1.18.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
# Data manipulation
import pandas as pd
import numpy as np

# Data preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# Model Training

#This notebook trains and evaluates multiple machine learning models for fraud detection using the engineered dataset. 
#The workflow includes data preparation, experiment tracking with MLflow, model training, performance evaluation, and model selection. The best-performing model will be used in the explainability stage of the proposed Explainable AI (XAI) fraud detection framework.
# Logistic Regression
# Random Forest
# XGBoost
# Model Evaluation
%pip install lightgbm
# Data manipulation
import pandas as pd
import numpy as np

# Data preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Machine learning models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# Model evaluation
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# Experiment tracking
import mlflow
import mlflow.sklearn

# Model persistence
import joblib

# Timing
import time

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option("display.max_columns", None)

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
# Loading Datase
# Load the engineered dataset
data = pd.read_csv("../Data/engineered_fraud_dataset.csv")

# Display the first five rows
data.head()
## Dataset Overview

#The engineered dataset is loaded and inspected to confirm that all features have been successfully imported and are ready for model training. This step verifies the dataset structure, identifies any missing values, and confirms the data types of each variable.
# Display the first five rows
data.head()

# Display dataset dimensions
print("Dataset Shape:", data.shape)

# Display column names
print("Columns:")
print(data.columns.tolist())

# Check for missing values
print("Missing Values:")
print(data.isnull().sum())

# Check data types
print("Data Types:")
print(data.dtypes)
## Identify Feature Types

#The dataset contains both numerical and categorical variables. Identifying feature types is necessary before applying preprocessing techniques such as one-hot encoding and feature scaling.
# Separate numerical and categorical columns
numerical_cols = data.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = data.select_dtypes(include=['object']).columns.tolist()

print("Numerical Features:")
print(numerical_cols)

print("\nCategorical Features:")
print(categorical_cols)
## Encode Categorical Variables

#Machine learning algorithms require numerical input. Therefore, the categorical variables are transformed into numerical representations using one-hot encoding.
# One-hot encode categorical variables
data = pd.get_dummies(
    data,
    columns=categorical_cols,
    drop_first=True
)

print("Dataset Shape After Encoding:", data.shape)

data.head()
bool_columns = data.select_dtypes(include='bool').columns

data[bool_columns] = data[bool_columns].astype(int)

print(data.head())
## Define Features and Target Variable

#The dataset is divided into input features (X) and the target variable (y). The target variable is `fraud_flag`, while all remaining variables are used as predictors for fraud detection.
# Define features and target variable
X = data.drop('fraud_flag', axis=1)
y = data['fraud_flag']

print("Feature Matrix Shape:", X.shape)
print("Target Variable Shape:", y.shape)
#checking the distribution of the target variable

print("Target Variable Distribution:")
print(y.value_counts())

print("\nTarget Variable Percentage:")
print(y.value_counts(normalize=True) * 100)
## Train-Test Split

#The dataset is divided into training and testing subsets using an 80:20 ratio. Stratified sampling is applied to preserve the class distribution of fraudulent and non-fraudulent transactions in both datasets.
from sklearn.model_selection import train_test_split

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y)


# Display dataset sizes
print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)
print("Training Target:", y_train.shape)
print("Testing Target:", y_test.shape)
# Model Training and Evaluation

## 1. Baseline Model Evaluation

### Logistic Regression (Baseline)
#- Train model
#- Evaluate model
#- Record results

### LightGBM (Default Parameters)
#- Train model
#- Evaluate model
#- Record results

### Baseline Model Comparison
#(results_df)
from sklearn.preprocessing import StandardScaler

# Create the scaler
scaler = StandardScaler()

# Fit only on the training data
X_train_scaled = scaler.fit_transform(X_train)

# Apply the same transformation to the test data
X_test_scaled = scaler.transform(X_test)
### LOGISTIC REGRESSION MODEL
# Create an empty list to store model results
results = []
import time

# Start training timer
start_train = time.time()

# Create the model
lr_model = LogisticRegression(
    random_state=42,
    max_iter=1000
)

# Train the model
lr_model.fit(X_train_scaled, y_train)

# End training timer
end_train = time.time()

# Calculate training time
training_time = end_train - start_train

print("Logistic Regression trained successfully!")
print(f"Training Time: {training_time:.4f} seconds")
## prediction and evaluation 

# Start prediction timer
start_pred = time.time()

# Make predictions
y_pred_lr = lr_model.predict(X_test_scaled)
y_prob_lr = lr_model.predict_proba(X_test_scaled)[:, 1]

# End prediction timer
end_pred = time.time()

# Calculate prediction time
prediction_time = end_pred - start_pred

print(f"Prediction Time: {prediction_time:.6f} seconds")
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred_lr)
precision = precision_score(y_test, y_pred_lr)
recall = recall_score(y_test, y_pred_lr)
f1 = f1_score(y_test, y_pred_lr)
roc_auc = roc_auc_score(y_test, y_prob_lr)

# Display the results
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"ROC-AUC: {roc_auc:.4f}")
print(classification_report(y_test, y_pred_lr))
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)
results.append({
    "Model": "Logistic Regression",
    "Training Time (s)": training_time,
    "Prediction Time (s)": prediction_time,
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1 Score": f1,
    "ROC-AUC": roc_auc
})
## XGBOOST MODEL
import time

# Start training timer
start_train = time.time()

# Create the XGBoost model
xgb_model = XGBClassifier(
    random_state=42,
    eval_metric='logloss'
)

# Train the model
xgb_model.fit(X_train, y_train)

# End training timer
end_train = time.time()

# Calculate training time
training_time = end_train - start_train

print("XGBoost model trained successfully!")
print(f"Training Time: {training_time:.4f} seconds")
# Start prediction timer
start_pred = time.time()

# Make predictions
y_pred_xgb = xgb_model.predict(X_test)
y_prob_xgb = xgb_model.predict_proba(X_test)[:, 1]

# End prediction timer
end_pred = time.time()

# Calculate prediction time
prediction_time = end_pred - start_pred

print(f"Prediction Time: {prediction_time:.6f} seconds")
##Evaluation metrics

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred_xgb)
precision = precision_score(y_test, y_pred_xgb)
recall = recall_score(y_test, y_pred_xgb)
f1 = f1_score(y_test, y_pred_xgb)
roc_auc = roc_auc_score(y_test, y_prob_xgb)

# Display the results
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"ROC-AUC: {roc_auc:.4f}")

##### classisfication report 
print(classification_report(y_test, y_pred_xgb))
#### confusion matrix
cm = confusion_matrix(y_test, y_pred_xgb)
print(cm)
#### Store Result
results.append({
    "Model": "XGBoost",
    "Training Time (s)": training_time,
    "Prediction Time (s)": prediction_time,
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1 Score": f1,
    "ROC-AUC": roc_auc})
## lightGBM Model
import time

# Start training timer
start_train = time.time()

# Create the LightGBM model
lgbm_model = LGBMClassifier(
    random_state=42
)

# Train the model
lgbm_model.fit(X_train, y_train)

# End training timer
end_train = time.time()

# Calculate training time
training_time = end_train - start_train

print("LightGBM model trained successfully!")
print(f"Training Time: {training_time:.4f} seconds")
# Start prediction timer
start_pred = time.time()

# Make predictions
y_pred_lgbm = lgbm_model.predict(X_test)
y_prob_lgbm = lgbm_model.predict_proba(X_test)[:, 1]

# End prediction timer
end_pred = time.time()

# Calculate prediction time
prediction_time = end_pred - start_pred

print(f"Prediction Time: {prediction_time:.6f} seconds")
accuracy = accuracy_score(y_test, y_pred_lgbm)
precision = precision_score(y_test, y_pred_lgbm)
recall = recall_score(y_test, y_pred_lgbm)
f1 = f1_score(y_test, y_pred_lgbm)
roc_auc = roc_auc_score(y_test, y_prob_lgbm)

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"ROC-AUC: {roc_auc:.4f}")
#### Classification 
print(classification_report(y_test, y_pred_lgbm))
### confusion matrix
cm = confusion_matrix(y_test, y_pred_lgbm)
print(cm)
### Store the data
results.append({
    "Model": "LightGBM",
    "Training Time (s)": training_time,
    "Prediction Time (s)": prediction_time,
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1 Score": f1,
    "ROC-AUC": roc_auc
})
## Comparing the models 
results_df = pd.DataFrame(results)
results_df
## Model Optimization Using Hyperparameter Tuning

## Hyperparameter Tuning - XGBoost

### Hyperparameter Tuning - LightGBM

### Optimized Model Comparison

from sklearn.model_selection import RandomizedSearchCV
# Define the hyperparameter search space
xgb_param_grid = {
    "n_estimators": [100, 200, 300],
    "max_depth": [3, 5, 7],
    "learning_rate": [0.01, 0.05, 0.1],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]}
### RandomizedSearchCV object
# Create the Randomized Search object
xgb_random = RandomizedSearchCV(
    estimator=XGBClassifier(
        random_state=42,
        eval_metric="logloss"
    ),
    param_distributions=xgb_param_grid,
    n_iter=20,
    scoring="f1",
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)
### ESTIMATOR
estimator=XGBClassifier(...)
param_distributions=xgb_param_grid
n_iter=20
### performing hyperparameter tuning 
# Perform hyperparameter tuning
xgb_random.fit(X_train, y_train)

print("Hyperparameter tuning completed!")
print("Best Parameters:")
print(xgb_random.best_params_)
print("Best F1 Score:")
print(xgb_random.best_score_)
### Train the Optimized XGBoost Model
import time
from xgboost import XGBClassifier

# Start training timer
start_train = time.time()

# Create the optimized model
xgb_optimized = XGBClassifier(
    n_estimators=100,
    max_depth=5,
    learning_rate=0.05,
    subsample=1.0,
    colsample_bytree=1.0,
    random_state=42,
    eval_metric="logloss"
)

# Train the model
xgb_optimized.fit(X_train, y_train)

# End training timer
end_train = time.time()

training_time = end_train - start_train

print("Optimized XGBoost trained successfully!")
print(f"Training Time: {training_time:.4f} seconds")
### PREDICTION
# Start prediction timer
start_pred = time.time()

# Make predictions
y_pred_xgb_opt = xgb_optimized.predict(X_test)
y_prob_xgb_opt = xgb_optimized.predict_proba(X_test)[:, 1]

# End prediction timer
end_pred = time.time()

# Calculate prediction time
prediction_time = end_pred - start_pred

print(f"Prediction Time: {prediction_time:.6f} seconds")
# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred_xgb_opt)
precision = precision_score(y_test, y_pred_xgb_opt)
recall = recall_score(y_test, y_pred_xgb_opt)
f1 = f1_score(y_test, y_pred_xgb_opt)
roc_auc = roc_auc_score(y_test, y_prob_xgb_opt)

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"ROC-AUC: {roc_auc:.4f}")
print(classification_report(y_test, y_pred_xgb_opt))
cm = confusion_matrix(y_test, y_pred_xgb_opt)
print(cm)
optimized_results = []
optimized_results.append({
    "Model": "Optimized XGBoost",
    "Training Time (s)": training_time,
    "Prediction Time (s)": prediction_time,
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1 Score": f1,
    "ROC-AUC": roc_auc
})
### Hyperparameter Tuning – LightGBM
# Define the hyperparameter search space
lgbm_param_grid = {
    "n_estimators": [100, 200, 300],
    "learning_rate": [0.01, 0.05, 0.1],
    "max_depth": [3, 5, 7],
    "num_leaves": [31, 50, 70],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]
}
### RandomizedSearchCV Object
# Create the Randomized Search object
lgbm_random = RandomizedSearchCV(
    estimator=LGBMClassifier(
        random_state=42
    ),
    param_distributions=lgbm_param_grid,
    n_iter=20,
    scoring="f1",
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)
### Performing hyperparameter tuning 
# Perform hyperparameter tuning
lgbm_random.fit(X_train, y_train)

print("LightGBM hyperparameter tuning completed!")
print("Best Parameters:")
print(lgbm_random.best_params_)
print("Best F1 Score:")
print(lgbm_random.best_score_)
### OPTIMIZING THE MODEL 
import time
from lightgbm import LGBMClassifier

# Start training timer
start_train = time.time()

# Create the optimized LightGBM model
lgbm_optimized = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.01,
    max_depth=5,
    num_leaves=70,
    subsample=0.8,
    colsample_bytree=1.0,
    random_state=42
)

# Train the model
lgbm_optimized.fit(X_train, y_train)

# End training timer
end_train = time.time()

training_time = end_train - start_train

print("Optimized LightGBM trained successfully!")
print(f"Training Time: {training_time:.4f} seconds")
# Start prediction timer
start_pred = time.time()

y_pred_lgbm_opt = lgbm_optimized.predict(X_test)
y_prob_lgbm_opt = lgbm_optimized.predict_proba(X_test)[:, 1]

end_pred = time.time()

prediction_time = end_pred - start_pred

print(f"Prediction Time: {prediction_time:.6f} seconds")
accuracy = accuracy_score(y_test, y_pred_lgbm_opt)
precision = precision_score(y_test, y_pred_lgbm_opt)
recall = recall_score(y_test, y_pred_lgbm_opt)
f1 = f1_score(y_test, y_pred_lgbm_opt)
roc_auc = roc_auc_score(y_test, y_prob_lgbm_opt)

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"ROC-AUC: {roc_auc:.4f}")
print(classification_report(y_test, y_pred_lgbm_opt))
cm = confusion_matrix(y_test, y_pred_lgbm_opt)
print(cm)
optimized_results.append({
    "Model": "Optimized LightGBM",
    "Training Time (s)": training_time,
    "Prediction Time (s)": prediction_time,
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1 Score": f1,
    "ROC-AUC": roc_auc})
## Final Model Comparison and Selection
import pandas as pd

# Baseline model results
results_df = pd.DataFrame(results)

# Optimized model results
optimized_results_df = pd.DataFrame(optimized_results)
print("Baseline Model Performance")
display(results_df)

print("Optimized Model Performance")
display(optimized_results_df)
print("Baseline Model Performance")
display(results_df)

print("Optimized Model Performance")
display(optimized_results_df)
# Combine baseline and optimized model results
final_results = pd.concat(
    [results_df, optimized_results_df],
    ignore_index=True
)

# Display the complete comparison table
print("Final Model Comparison")
display(final_results)
# Select the final model
final_model = lgbm_optimized

print("Final Selected Model: Optimized LightGBM")
import joblib

joblib.dump(lgbm_optimized, "final_lightgbm_model.joblib")
#grid_search = GridSearchCV(...)
### Model Selection

#The baseline and optimized machine learning models were compared using Accuracy, Precision, Recall, F1 Score, ROC-AUC, training time, and prediction time.

#Hyperparameter tuning improved the performance of both XGBoost and LightGBM compared to their default configurations.

#The Optimized LightGBM model achieved the strongest overall balance between classification performance and computational efficiency, recording the highest Accuracy (95.30%), Precision (82.77%), and F1 Score (80.74%), while maintaining a competitive Recall (78.80%) and ROC-AUC (97.79%).

#Based on these results, the Optimized LightGBM model was selected as the final model for the explainable AI fraud detection framework. This model will be used in the subsequent explainability, experiment tracking, and deployment stages of the project.
# Machine learning models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# Model evaluation
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# Experiment tracking
import mlflow
import mlflow.sklearn

# Model persistence
import joblib

# Timing
import time

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option("display.max_columns", None)

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

Requirement already satisfied: lightgbm in c:\Users\Olami\OneDrive\Documents\DATASCIENCEPROJECT\.venv-1\Lib\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in c:\Users\Olami\OneDrive\Documents\DATASCIENCEPROJECT\.venv-1\Lib\site-packages (from lightgbm) (2.4.6)
Requirement already satisfied: scipy in c:\Users\Olami\OneDrive\Documents\DATASCIENCEPROJECT\.venv-1\Lib\site-packages (from lightgbm) (1.18.0)
Note: you may need to restart the kernel to use updated packages.
Dataset Shape: (10000, 26)
Columns:
['transaction_amount', 'login_attempts', 'device_risk_score', 'transfer_frequency', 'anomaly_score', 'account_age_days', 'transaction_time_hour', 'failed_transactions_last_30d', 'avg_monthly_balance', 'daily_transaction_count', 'geo_distance_km', 'session_duration_minutes', 'transaction_velocity_score', 'payment_channel', 'authentication_type', 'card_present_flag', 'international_transaction_flag', 'suspicious_ip_flag', 'fraud_flag', 'new_account', 'high_value_transaction', 'high_login_attempts', 'high_velocity', 'night_transaction', 'far_distance_transaction', 'high_device_risk']
Missing Values:
transaction_amount                0
login_attempts                    0
device_risk_score                 0
transfer_frequency                0
anomaly_score                     0
account_age_days                  0
transaction_time_hour             0
failed_transactions_last_30d      0
avg_monthly_balance               0
daily_transaction_count           0
geo_distance_km                   0
session_duration_minutes          0
transaction_velocity_score        0
payment_channel                   0
authentication_type               0
card_present_flag                 0
international_transaction_flag    0
suspicious_ip_flag                0
fraud_flag                        0
new_account                       0
high_value_transaction            0
high_login_attempts               0
high_velocity                     0
night_transaction                 0
far_distance_transaction          0
high_device_risk                  0
dtype: int64
Data Types:
transaction_amount                float64
login_attempts                      int64
device_risk_score                 float64
transfer_frequency                  int64
anomaly_score                     float64
account_age_days                    int64
transaction_time_hour               int64
failed_transactions_last_30d        int64
avg_monthly_balance               float64
daily_transaction_count             int64
geo_distance_km                     int64
session_duration_minutes            int64
transaction_velocity_score        float64
payment_channel                    object
authentication_type                object
card_present_flag                   int64
international_transaction_flag      int64
suspicious_ip_flag                  int64
fraud_flag                          int64
new_account                         int64
high_value_transaction              int64
high_login_attempts                 int64
high_velocity                       int64
night_transaction                   int64
far_distance_transaction            int64
high_device_risk                    int64
dtype: object
Numerical Features:
['transaction_amount', 'login_attempts', 'device_risk_score', 'transfer_frequency', 'anomaly_score', 'account_age_days', 'transaction_time_hour', 'failed_transactions_last_30d', 'avg_monthly_balance', 'daily_transaction_count', 'geo_distance_km', 'session_duration_minutes', 'transaction_velocity_score', 'card_present_flag', 'international_transaction_flag', 'suspicious_ip_flag', 'fraud_flag', 'new_account', 'high_value_transaction', 'high_login_attempts', 'high_velocity', 'night_transaction', 'far_distance_transaction', 'high_device_risk']

Categorical Features:
['payment_channel', 'authentication_type']
Dataset Shape After Encoding: (10000, 30)
   transaction_amount  login_attempts  device_risk_score  transfer_frequency  \
0            17829.01               4               12.0                  13
1            16401.83               1               34.3                  17
2             9678.29               8               67.8                  39
3            19013.38               5               17.8                  42
4            13834.95               3               88.9                  63

   anomaly_score  account_age_days  transaction_time_hour  \
0           0.37              2354                     22
1           0.26              3181                     17
2           0.15              1390                      3
3           0.55              3716                     16
4           0.24              4694                     16

   failed_transactions_last_30d  avg_monthly_balance  daily_transaction_count  \
0                            25            112760.07                       63
1                            15            118899.52                       83
2                             2            408168.98                        9
3                             6             80771.69                       78
4                            10            382265.32                       17

   geo_distance_km  session_duration_minutes  transaction_velocity_score  \
0             3189                        92                        71.8
1              839                        63                        11.8
2             3938                        80                        35.7
3            11111                        11                        74.8
4             3171                        87                         0.0

   card_present_flag  international_transaction_flag  suspicious_ip_flag  \
0                  1                               1                   1
1                  0                               0                   1
2                  1                               0                   1
3                  1                               1                   0
4                  1                               0                   0

   fraud_flag  new_account  high_value_transaction  high_login_attempts  \
0           0            0                       0                    0
1           0            0                       0                    0
2           0            0                       0                    0
3           0            0                       1                    0
4           0            0                       0                    0

   high_velocity  night_transaction  far_distance_transaction  \
0              0                  1                         0
1              0                  0                         0
2              0                  1                         0
3              0                  0                         0
4              0                  0                         0

   high_device_risk  payment_channel_Mobile App  payment_channel_POS Terminal  \
0                 0                           0                             1
1                 0                           0                             0
2                 0                           0                             0
3                 0                           1                             0
4                 1                           1                             0

   payment_channel_Web Banking  authentication_type_OTP  \
0                            0                        1
1                            1                        0
2                            0                        1
3                            0                        1
4                            0                        1

   authentication_type_Password Only  \
0                                  0
1                                  0
2                                  0
3                                  0
4                                  0

   authentication_type_Two-Factor Authentication
0                                              0
1                                              0
2                                              0
3                                              0
4                                              0
Feature Matrix Shape: (10000, 29)
Target Variable Shape: (10000,)
Target Variable Distribution:
fraud_flag
0    8749
1    1251
Name: count, dtype: int64

Target Variable Percentage:
fraud_flag
0    87.49
1    12.51
Name: proportion, dtype: float64
Training Features: (8000, 29)
Testing Features: (2000, 29)
Training Target: (8000,)
Testing Target: (2000,)
Logistic Regression trained successfully!
Training Time: 0.0144 seconds
Prediction Time: 0.001329 seconds
Accuracy: 0.9515
Precision: 0.8255
Recall: 0.7760
F1 Score: 0.8000
ROC-AUC: 0.9793
              precision    recall  f1-score   support

           0       0.97      0.98      0.97      1750
           1       0.83      0.78      0.80       250

    accuracy                           0.95      2000
   macro avg       0.90      0.88      0.89      2000
weighted avg       0.95      0.95      0.95      2000

[[1709   41]
 [  56  194]]

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

XGBoost model trained successfully!
Training Time: 0.3863 seconds
Prediction Time: 0.022501 seconds
Accuracy: 0.9460
Precision: 0.7863
Recall: 0.7800
F1 Score: 0.7831
ROC-AUC: 0.9764
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1750
           1       0.79      0.78      0.78       250

    accuracy                           0.95      2000
   macro avg       0.88      0.87      0.88      2000
weighted avg       0.95      0.95      0.95      2000

[[1697   53]
 [  55  195]]
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 1001, number of negative: 6999
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000601 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2048
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 29
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.125125 -> initscore=-1.944768
[LightGBM] [Info] Start training from score -1.944768
LightGBM model trained successfully!
Training Time: 0.1535 seconds
Prediction Time: 0.011466 seconds
Accuracy: 0.9510
Precision: 0.8115
Recall: 0.7920
F1 Score: 0.8016
ROC-AUC: 0.9785
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1750
           1       0.81      0.79      0.80       250

    accuracy                           0.95      2000
   macro avg       0.89      0.88      0.89      2000
weighted avg       0.95      0.95      0.95      2000

[[1704   46]
 [  52  198]]
Fitting 5 folds for each of 20 candidates, totalling 100 fits

c:\Users\Olami\OneDrive\Documents\DATASCIENCEPROJECT\.venv-1\Lib\site-packages\xgboost\core.py:550: FutureWarning: Pass `objective` as keyword args.
  warnings.warn(msg, FutureWarning)

Hyperparameter tuning completed!
Best Parameters:
{'subsample': 1.0, 'n_estimators': 100, 'max_depth': 5, 'learning_rate': 0.05, 'colsample_bytree': 1.0}
Best F1 Score:
0.7907593810183672
Optimized XGBoost trained successfully!
Training Time: 0.1656 seconds
Prediction Time: 0.016325 seconds
Accuracy: 0.9525
Precision: 0.8189
Recall: 0.7960
F1 Score: 0.8073
ROC-AUC: 0.9777
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1750
           1       0.82      0.80      0.81       250

    accuracy                           0.95      2000
   macro avg       0.89      0.89      0.89      2000
weighted avg       0.95      0.95      0.95      2000

[[1706   44]
 [  51  199]]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 1001, number of negative: 6999
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001716 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2048
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 29
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.125125 -> initscore=-1.944768
[LightGBM] [Info] Start training from score -1.944768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

,Model,Training Time (s),Prediction Time (s),Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Logistic Regression,0.014429,0.001329,0.9515,0.825532,0.776,0.800000,0.979312
1,XGBoost,0.386292,0.022501,0.9460,0.786290,0.780,0.783133,0.976441
2,LightGBM,0.153457,0.011466,0.9510,0.811475,0.792,0.801619,0.978494

Optimized Model Performance

,Model,Training Time (s),Prediction Time (s),Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Optimized XGBoost,0.165641,0.016325,0.9525,0.818930,0.796,0.807302,0.977689
1,Optimized LightGBM,0.555625,0.022344,0.9530,0.827731,0.788,0.807377,0.977928

Baseline Model Performance

,Model,Training Time (s),Prediction Time (s),Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Logistic Regression,0.014429,0.001329,0.9515,0.825532,0.776,0.800000,0.979312
1,XGBoost,0.386292,0.022501,0.9460,0.786290,0.780,0.783133,0.976441
2,LightGBM,0.153457,0.011466,0.9510,0.811475,0.792,0.801619,0.978494

Optimized Model Performance

,Model,Training Time (s),Prediction Time (s),Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Optimized XGBoost,0.165641,0.016325,0.9525,0.818930,0.796,0.807302,0.977689
1,Optimized LightGBM,0.555625,0.022344,0.9530,0.827731,0.788,0.807377,0.977928

Final Model Comparison

,Model,Training Time (s),Prediction Time (s),Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Logistic Regression,0.014429,0.001329,0.9515,0.825532,0.776,0.800000,0.979312
1,XGBoost,0.386292,0.022501,0.9460,0.786290,0.780,0.783133,0.976441
2,LightGBM,0.153457,0.011466,0.9510,0.811475,0.792,0.801619,0.978494
3,Optimized XGBoost,0.165641,0.016325,0.9525,0.818930,0.796,0.807302,0.977689
4,Optimized LightGBM,0.555625,0.022344,0.9530,0.827731,0.788,0.807377,0.977928

Final Selected Model: Optimized LightGBM

# Loading Datase

In [6]:
# Load the engineered dataset
data = pd.read_csv("../Data/engineered_fraud_dataset.csv")

# Display the first five rows
data.head()

,transaction_amount,login_attempts,device_risk_score,transfer_frequency,anomaly_score,account_age_days,transaction_time_hour,failed_transactions_last_30d,avg_monthly_balance,daily_transaction_count,geo_distance_km,session_duration_minutes,transaction_velocity_score,payment_channel,authentication_type,card_present_flag,international_transaction_flag,suspicious_ip_flag,fraud_flag,new_account,high_value_transaction,high_login_attempts,high_velocity,night_transaction,far_distance_transaction,high_device_risk
0,17829.01,4,12.0,13,0.37,2354,22,25,112760.07,63,3189,92,71.8,POS Terminal,OTP,1,1,1,0,0,0,0,0,1,0,0
1,16401.83,1,34.3,17,0.26,3181,17,15,118899.52,83,839,63,11.8,Web Banking,Biometric,0,0,1,0,0,0,0,0,0,0,0
2,9678.29,8,67.8,39,0.15,1390,3,2,408168.98,9,3938,80,35.7,ATM,OTP,1,0,1,0,0,0,0,0,1,0,0
3,19013.38,5,17.8,42,0.55,3716,16,6,80771.69,78,11111,11,74.8,Mobile App,OTP,1,1,0,0,0,1,0,0,0,0,0
4,13834.95,3,88.9,63,0.24,4694,16,10,382265.32,17,3171,87,0.0,Mobile App,OTP,1,0,0,0,0,0,0,0,0,0,1

## Dataset Overview

The engineered dataset is loaded and inspected to confirm that all features have been successfully imported and are ready for model training. This step verifies the dataset structure, identifies any missing values, and confirms the data types of each variable.

In [7]:
# Display the first five rows
data.head()

# Display dataset dimensions
print("Dataset Shape:", data.shape)

# Display column names
print("Columns:")
print(data.columns.tolist())

# Check for missing values
print("Missing Values:")
print(data.isnull().sum())

# Check data types
print("Data Types:")
print(data.dtypes)

Dataset Shape: (10000, 26)
Columns:
['transaction_amount', 'login_attempts', 'device_risk_score', 'transfer_frequency', 'anomaly_score', 'account_age_days', 'transaction_time_hour', 'failed_transactions_last_30d', 'avg_monthly_balance', 'daily_transaction_count', 'geo_distance_km', 'session_duration_minutes', 'transaction_velocity_score', 'payment_channel', 'authentication_type', 'card_present_flag', 'international_transaction_flag', 'suspicious_ip_flag', 'fraud_flag', 'new_account', 'high_value_transaction', 'high_login_attempts', 'high_velocity', 'night_transaction', 'far_distance_transaction', 'high_device_risk']
Missing Values:
transaction_amount                0
login_attempts                    0
device_risk_score                 0
transfer_frequency                0
anomaly_score                     0
account_age_days                  0
transaction_time_hour             0
failed_transactions_last_30d      0
avg_monthly_balance               0
daily_transaction_count           0
geo_distance_km                   0
session_duration_minutes          0
transaction_velocity_score        0
payment_channel                   0
authentication_type               0
card_present_flag                 0
international_transaction_flag    0
suspicious_ip_flag                0
fraud_flag                        0
new_account                       0
high_value_transaction            0
high_login_attempts               0
high_velocity                     0
night_transaction                 0
far_distance_transaction          0
high_device_risk                  0
dtype: int64
Data Types:
transaction_amount                float64
login_attempts                      int64
device_risk_score                 float64
transfer_frequency                  int64
anomaly_score                     float64
account_age_days                    int64
transaction_time_hour               int64
failed_transactions_last_30d        int64
avg_monthly_balance               float64
daily_transaction_count             int64
geo_distance_km                     int64
session_duration_minutes            int64
transaction_velocity_score        float64
payment_channel                    object
authentication_type                object
card_present_flag                   int64
international_transaction_flag      int64
suspicious_ip_flag                  int64
fraud_flag                          int64
new_account                         int64
high_value_transaction              int64
high_login_attempts                 int64
high_velocity                       int64
night_transaction                   int64
far_distance_transaction            int64
high_device_risk                    int64
dtype: object

## Identify Feature Types

The dataset contains both numerical and categorical variables. Identifying feature types is necessary before applying preprocessing techniques such as one-hot encoding and feature scaling.

In [8]:
# Separate numerical and categorical columns
numerical_cols = data.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = data.select_dtypes(include=['object']).columns.tolist()

print("Numerical Features:")
print(numerical_cols)

print("\nCategorical Features:")
print(categorical_cols)

Numerical Features:
['transaction_amount', 'login_attempts', 'device_risk_score', 'transfer_frequency', 'anomaly_score', 'account_age_days', 'transaction_time_hour', 'failed_transactions_last_30d', 'avg_monthly_balance', 'daily_transaction_count', 'geo_distance_km', 'session_duration_minutes', 'transaction_velocity_score', 'card_present_flag', 'international_transaction_flag', 'suspicious_ip_flag', 'fraud_flag', 'new_account', 'high_value_transaction', 'high_login_attempts', 'high_velocity', 'night_transaction', 'far_distance_transaction', 'high_device_risk']

Categorical Features:
['payment_channel', 'authentication_type']

## Encode Categorical Variables

Machine learning algorithms require numerical input. Therefore, the categorical variables are transformed into numerical representations using one-hot encoding.

In [9]:
# One-hot encode categorical variables
data = pd.get_dummies(
    data,
    columns=categorical_cols,
    drop_first=True
)

print("Dataset Shape After Encoding:", data.shape)

data.head()

Dataset Shape After Encoding: (10000, 30)

,transaction_amount,login_attempts,device_risk_score,transfer_frequency,anomaly_score,account_age_days,transaction_time_hour,failed_transactions_last_30d,avg_monthly_balance,daily_transaction_count,geo_distance_km,session_duration_minutes,transaction_velocity_score,card_present_flag,international_transaction_flag,suspicious_ip_flag,fraud_flag,new_account,high_value_transaction,high_login_attempts,high_velocity,night_transaction,far_distance_transaction,high_device_risk,payment_channel_Mobile App,payment_channel_POS Terminal,payment_channel_Web Banking,authentication_type_OTP,authentication_type_Password Only,authentication_type_Two-Factor Authentication
0,17829.01,4,12.0,13,0.37,2354,22,25,112760.07,63,3189,92,71.8,1,1,1,0,0,0,0,0,1,0,0,False,True,False,True,False,False
1,16401.83,1,34.3,17,0.26,3181,17,15,118899.52,83,839,63,11.8,0,0,1,0,0,0,0,0,0,0,0,False,False,True,False,False,False
2,9678.29,8,67.8,39,0.15,1390,3,2,408168.98,9,3938,80,35.7,1,0,1,0,0,0,0,0,1,0,0,False,False,False,True,False,False
3,19013.38,5,17.8,42,0.55,3716,16,6,80771.69,78,11111,11,74.8,1,1,0,0,0,1,0,0,0,0,0,True,False,False,True,False,False
4,13834.95,3,88.9,63,0.24,4694,16,10,382265.32,17,3171,87,0.0,1,0,0,0,0,0,0,0,0,0,1,True,False,False,True,False,False

In [10]:
bool_columns = data.select_dtypes(include='bool').columns

data[bool_columns] = data[bool_columns].astype(int)

print(data.head())

   transaction_amount  login_attempts  device_risk_score  transfer_frequency  \
0            17829.01               4               12.0                  13
1            16401.83               1               34.3                  17
2             9678.29               8               67.8                  39
3            19013.38               5               17.8                  42
4            13834.95               3               88.9                  63

   anomaly_score  account_age_days  transaction_time_hour  \
0           0.37              2354                     22
1           0.26              3181                     17
2           0.15              1390                      3
3           0.55              3716                     16
4           0.24              4694                     16

   failed_transactions_last_30d  avg_monthly_balance  daily_transaction_count  \
0                            25            112760.07                       63
1                            15            118899.52                       83
2                             2            408168.98                        9
3                             6             80771.69                       78
4                            10            382265.32                       17

   geo_distance_km  session_duration_minutes  transaction_velocity_score  \
0             3189                        92                        71.8
1              839                        63                        11.8
2             3938                        80                        35.7
3            11111                        11                        74.8
4             3171                        87                         0.0

   card_present_flag  international_transaction_flag  suspicious_ip_flag  \
0                  1                               1                   1
1                  0                               0                   1
2                  1                               0                   1
3                  1                               1                   0
4                  1                               0                   0

   fraud_flag  new_account  high_value_transaction  high_login_attempts  \
0           0            0                       0                    0
1           0            0                       0                    0
2           0            0                       0                    0
3           0            0                       1                    0
4           0            0                       0                    0

   high_velocity  night_transaction  far_distance_transaction  \
0              0                  1                         0
1              0                  0                         0
2              0                  1                         0
3              0                  0                         0
4              0                  0                         0

   high_device_risk  payment_channel_Mobile App  payment_channel_POS Terminal  \
0                 0                           0                             1
1                 0                           0                             0
2                 0                           0                             0
3                 0                           1                             0
4                 1                           1                             0

   payment_channel_Web Banking  authentication_type_OTP  \
0                            0                        1
1                            1                        0
2                            0                        1
3                            0                        1
4                            0                        1

   authentication_type_Password Only  \
0                                  0
1                                  0
2                                  0
3                                  0
4                                  0

   authentication_type_Two-Factor Authentication
0                                              0
1                                              0
2                                              0
3                                              0
4                                              0

## Define Features and Target Variable

The dataset is divided into input features (X) and the target variable (y). The target variable is `fraud_flag`, while all remaining variables are used as predictors for fraud detection.

In [11]:
# Define features and target variable
X = data.drop('fraud_flag', axis=1)
y = data['fraud_flag']

print("Feature Matrix Shape:", X.shape)
print("Target Variable Shape:", y.shape)

Feature Matrix Shape: (10000, 29)
Target Variable Shape: (10000,)

In [12]:
#checking the distribution of the target variable

print("Target Variable Distribution:")
print(y.value_counts())

print("\nTarget Variable Percentage:")
print(y.value_counts(normalize=True) * 100)

Target Variable Distribution:
fraud_flag
0    8749
1    1251
Name: count, dtype: int64

Target Variable Percentage:
fraud_flag
0    87.49
1    12.51
Name: proportion, dtype: float64

## Train-Test Split

The dataset is divided into training and testing subsets using an 80:20 ratio. Stratified sampling is applied to preserve the class distribution of fraudulent and non-fraudulent transactions in both datasets.

In [13]:
from sklearn.model_selection import train_test_split

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Display dataset sizes
print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)
print("Training Target:", y_train.shape)
print("Testing Target:", y_test.shape)

Training Features: (8000, 29)
Testing Features: (2000, 29)
Training Target: (8000,)
Testing Target: (2000,)

# Model Training and Evaluation

## 1. Baseline Model Evaluation

### Logistic Regression (Baseline)
- Train model
- Evaluate model
- Record results

### XGBoost (Default Parameters)
- Train model
- Evaluate model
- Record results

### LightGBM (Default Parameters)
- Train model
- Evaluate model
- Record results

### Baseline Model Comparison
(results_df)

In [14]:
from sklearn.preprocessing import StandardScaler

# Create the scaler
scaler = StandardScaler()

# Fit only on the training data
X_train_scaled = scaler.fit_transform(X_train)

# Apply the same transformation to the test data
X_test_scaled = scaler.transform(X_test)

### LOGISTIC REGRESSION MODEL

In [15]:
# Create an empty list to store model results
results = []

In [16]:
import time

# Start training timer
start_train = time.time()

# Create the model
lr_model = LogisticRegression(
    random_state=42,
    max_iter=1000
)

# Train the model
lr_model.fit(X_train_scaled, y_train)

# End training timer
end_train = time.time()

# Calculate training time
training_time = end_train - start_train

print("Logistic Regression trained successfully!")
print(f"Training Time: {training_time:.4f} seconds")

Logistic Regression trained successfully!
Training Time: 0.0617 seconds

In [17]:
## prediction and evaluation 

# Start prediction timer
start_pred = time.time()

# Make predictions
y_pred_lr = lr_model.predict(X_test_scaled)
y_prob_lr = lr_model.predict_proba(X_test_scaled)[:, 1]

# End prediction timer
end_pred = time.time()

# Calculate prediction time
prediction_time = end_pred - start_pred

print(f"Prediction Time: {prediction_time:.6f} seconds")

Prediction Time: 0.002329 seconds

In [18]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred_lr)
precision = precision_score(y_test, y_pred_lr)
recall = recall_score(y_test, y_pred_lr)
f1 = f1_score(y_test, y_pred_lr)
roc_auc = roc_auc_score(y_test, y_prob_lr)

# Display the results
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"ROC-AUC: {roc_auc:.4f}")

Accuracy: 0.9515
Precision: 0.8255
Recall: 0.7760
F1 Score: 0.8000
ROC-AUC: 0.9793

In [19]:
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.97      0.98      0.97      1750
           1       0.83      0.78      0.80       250

    accuracy                           0.95      2000
   macro avg       0.90      0.88      0.89      2000
weighted avg       0.95      0.95      0.95      2000

In [20]:
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)

[[1709   41]
 [  56  194]]

In [21]:
results.append({
    "Model": "Logistic Regression",
    "Training Time (s)": training_time,
    "Prediction Time (s)": prediction_time,
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1 Score": f1,
    "ROC-AUC": roc_auc
})

## XGBOOST MODEL

In [22]:
import time

# Start training timer
start_train = time.time()

# Create the XGBoost model
xgb_model = XGBClassifier(
    random_state=42,
    eval_metric='logloss'
)

# Train the model
xgb_model.fit(X_train, y_train)

# End training timer
end_train = time.time()

# Calculate training time
training_time = end_train - start_train

print("XGBoost model trained successfully!")
print(f"Training Time: {training_time:.4f} seconds")

XGBoost model trained successfully!
Training Time: 0.2911 seconds

In [23]:
# Start prediction timer
start_pred = time.time()

# Make predictions
y_pred_xgb = xgb_model.predict(X_test)
y_prob_xgb = xgb_model.predict_proba(X_test)[:, 1]

# End prediction timer
end_pred = time.time()

# Calculate prediction time
prediction_time = end_pred - start_pred

print(f"Prediction Time: {prediction_time:.6f} seconds")

Prediction Time: 0.026951 seconds

In [24]:
##Evaluation metrics

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred_xgb)
precision = precision_score(y_test, y_pred_xgb)
recall = recall_score(y_test, y_pred_xgb)
f1 = f1_score(y_test, y_pred_xgb)
roc_auc = roc_auc_score(y_test, y_prob_xgb)

# Display the results
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"ROC-AUC: {roc_auc:.4f}")

Accuracy: 0.9460
Precision: 0.7863
Recall: 0.7800
F1 Score: 0.7831
ROC-AUC: 0.9764

##### classisfication report

In [25]:
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1750
           1       0.79      0.78      0.78       250

    accuracy                           0.95      2000
   macro avg       0.88      0.87      0.88      2000
weighted avg       0.95      0.95      0.95      2000

#### confusion matrix

In [26]:
cm = confusion_matrix(y_test, y_pred_xgb)
print(cm)

[[1697   53]
 [  55  195]]

#### Store Result

In [27]:
results.append({
    "Model": "XGBoost",
    "Training Time (s)": training_time,
    "Prediction Time (s)": prediction_time,
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1 Score": f1,
    "ROC-AUC": roc_auc})

## lightGBM Model

In [28]:
import time

# Start training timer
start_train = time.time()

# Create the LightGBM model
lgbm_model = LGBMClassifier(
    random_state=42
)

# Train the model
lgbm_model.fit(X_train, y_train)

# End training timer
end_train = time.time()

# Calculate training time
training_time = end_train - start_train

print("LightGBM model trained successfully!")
print(f"Training Time: {training_time:.4f} seconds")

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 1001, number of negative: 6999
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.011098 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2048
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 29
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.125125 -> initscore=-1.944768
[LightGBM] [Info] Start training from score -1.944768
LightGBM model trained successfully!
Training Time: 0.4178 seconds

In [29]:
# Start prediction timer
start_pred = time.time()

# Make predictions
y_pred_lgbm = lgbm_model.predict(X_test)
y_prob_lgbm = lgbm_model.predict_proba(X_test)[:, 1]

# End prediction timer
end_pred = time.time()

# Calculate prediction time
prediction_time = end_pred - start_pred

print(f"Prediction Time: {prediction_time:.6f} seconds")

Prediction Time: 0.020337 seconds

In [30]:
accuracy = accuracy_score(y_test, y_pred_lgbm)
precision = precision_score(y_test, y_pred_lgbm)
recall = recall_score(y_test, y_pred_lgbm)
f1 = f1_score(y_test, y_pred_lgbm)
roc_auc = roc_auc_score(y_test, y_prob_lgbm)

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"ROC-AUC: {roc_auc:.4f}")

Accuracy: 0.9510
Precision: 0.8115
Recall: 0.7920
F1 Score: 0.8016
ROC-AUC: 0.9785

#### Classification

In [31]:
print(classification_report(y_test, y_pred_lgbm))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1750
           1       0.81      0.79      0.80       250

    accuracy                           0.95      2000
   macro avg       0.89      0.88      0.89      2000
weighted avg       0.95      0.95      0.95      2000

### confusion matrix

In [32]:
cm = confusion_matrix(y_test, y_pred_lgbm)
print(cm)

[[1704   46]
 [  52  198]]

### Store the data

In [33]:
results.append({
    "Model": "LightGBM",
    "Training Time (s)": training_time,
    "Prediction Time (s)": prediction_time,
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1 Score": f1,
    "ROC-AUC": roc_auc
})

## Comparing the models

In [34]:
results_df = pd.DataFrame(results)
results_df

,Model,Training Time (s),Prediction Time (s),Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Logistic Regression,0.061730,0.002329,0.9515,0.825532,0.776,0.800000,0.979312
1,XGBoost,0.291051,0.026951,0.9460,0.786290,0.780,0.783133,0.976441
2,LightGBM,0.417768,0.020337,0.9510,0.811475,0.792,0.801619,0.978494

## Model Optimization Using Hyperparameter Tuning

## Hyperparameter Tuning - XGBoost

### Hyperparameter Tuning - LightGBM

### Optimized Model Comparison

In [35]:
from sklearn.model_selection import RandomizedSearchCV

In [36]:
# Define the hyperparameter search space
xgb_param_grid = {
    "n_estimators": [100, 200, 300],
    "max_depth": [3, 5, 7],
    "learning_rate": [0.01, 0.05, 0.1],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]}

### RandomizedSearchCV object

In [37]:
# Create the Randomized Search object
xgb_random = RandomizedSearchCV(
    estimator=XGBClassifier(
        random_state=42,
        eval_metric="logloss"
    ),
    param_distributions=xgb_param_grid,
    n_iter=20,
    scoring="f1",
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

### ESTIMATOR

In [38]:
estimator=XGBClassifier(...)

c:\Users\Olami\OneDrive\Documents\DATASCIENCEPROJECT\.venv-1\Lib\site-packages\xgboost\core.py:550: FutureWarning: Pass `objective` as keyword args.
  warnings.warn(msg, FutureWarning)

In [39]:
param_distributions=xgb_param_grid

In [40]:
n_iter=20

### performing hyperparameter tuning

In [41]:
# Perform hyperparameter tuning
xgb_random.fit(X_train, y_train)

print("Hyperparameter tuning completed!")

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Hyperparameter tuning completed!

In [42]:
print("Best Parameters:")
print(xgb_random.best_params_)

Best Parameters:
{'subsample': 1.0, 'n_estimators': 100, 'max_depth': 5, 'learning_rate': 0.05, 'colsample_bytree': 1.0}

In [43]:
print("Best F1 Score:")
print(xgb_random.best_score_)

Best F1 Score:
0.7907593810183672

### Train the Optimized XGBoost Model

In [44]:
import time
from xgboost import XGBClassifier

# Start training timer
start_train = time.time()

# Create the optimized model
xgb_optimized = XGBClassifier(
    n_estimators=100,
    max_depth=5,
    learning_rate=0.05,
    subsample=1.0,
    colsample_bytree=1.0,
    random_state=42,
    eval_metric="logloss"
)

# Train the model
xgb_optimized.fit(X_train, y_train)

# End training timer
end_train = time.time()

training_time = end_train - start_train

print("Optimized XGBoost trained successfully!")
print(f"Training Time: {training_time:.4f} seconds")

Optimized XGBoost trained successfully!
Training Time: 0.2438 seconds

### PREDICTION

In [45]:
# Start prediction timer
start_pred = time.time()

# Make predictions
y_pred_xgb_opt = xgb_optimized.predict(X_test)
y_prob_xgb_opt = xgb_optimized.predict_proba(X_test)[:, 1]

# End prediction timer
end_pred = time.time()

# Calculate prediction time
prediction_time = end_pred - start_pred

print(f"Prediction Time: {prediction_time:.6f} seconds")

Prediction Time: 0.026451 seconds

In [46]:
# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred_xgb_opt)
precision = precision_score(y_test, y_pred_xgb_opt)
recall = recall_score(y_test, y_pred_xgb_opt)
f1 = f1_score(y_test, y_pred_xgb_opt)
roc_auc = roc_auc_score(y_test, y_prob_xgb_opt)

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"ROC-AUC: {roc_auc:.4f}")

Accuracy: 0.9525
Precision: 0.8189
Recall: 0.7960
F1 Score: 0.8073
ROC-AUC: 0.9777

In [47]:
print(classification_report(y_test, y_pred_xgb_opt))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1750
           1       0.82      0.80      0.81       250

    accuracy                           0.95      2000
   macro avg       0.89      0.89      0.89      2000
weighted avg       0.95      0.95      0.95      2000

In [48]:
cm = confusion_matrix(y_test, y_pred_xgb_opt)
print(cm)

[[1706   44]
 [  51  199]]

In [49]:
optimized_results = []

In [50]:
optimized_results.append({
    "Model": "Optimized XGBoost",
    "Training Time (s)": training_time,
    "Prediction Time (s)": prediction_time,
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1 Score": f1,
    "ROC-AUC": roc_auc
})

### Hyperparameter Tuning – LightGBM

In [51]:
# Define the hyperparameter search space
lgbm_param_grid = {
    "n_estimators": [100, 200, 300],
    "learning_rate": [0.01, 0.05, 0.1],
    "max_depth": [3, 5, 7],
    "num_leaves": [31, 50, 70],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]
}

### RandomizedSearchCV Object

In [52]:
# Create the Randomized Search object
lgbm_random = RandomizedSearchCV(
    estimator=LGBMClassifier(
        random_state=42
    ),
    param_distributions=lgbm_param_grid,
    n_iter=20,
    scoring="f1",
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

### Performing hyperparameter tuning

In [53]:
# Perform hyperparameter tuning
lgbm_random.fit(X_train, y_train)

print("LightGBM hyperparameter tuning completed!")

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 1001, number of negative: 6999
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001211 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2048
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 29
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.125125 -> initscore=-1.944768
[LightGBM] [Info] Start training from score -1.944768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [54]:
print("Best Parameters:")
print(lgbm_random.best_params_)

Best Parameters:
{'subsample': 0.8, 'num_leaves': 70, 'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.01, 'colsample_bytree': 1.0}

In [55]:
print("Best F1 Score:")
print(lgbm_random.best_score_)

Best F1 Score:
0.789027963783006

### OPTIMIZING THE MODEL

In [56]:
import time
from lightgbm import LGBMClassifier

# Start training timer
start_train = time.time()

# Create the optimized LightGBM model
lgbm_optimized = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.01,
    max_depth=5,
    num_leaves=70,
    subsample=0.8,
    colsample_bytree=1.0,
    random_state=42
)

# Train the model
lgbm_optimized.fit(X_train, y_train)

# End training timer
end_train = time.time()

training_time = end_train - start_train

print("Optimized LightGBM trained successfully!")
print(f"Training Time: {training_time:.4f} seconds")

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 1001, number of negative: 6999
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004287 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2048
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 29
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.125125 -> initscore=-1.944768
[LightGBM] [Info] Start training from score -1.944768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [57]:
# Start prediction timer
start_pred = time.time()

y_pred_lgbm_opt = lgbm_optimized.predict(X_test)
y_prob_lgbm_opt = lgbm_optimized.predict_proba(X_test)[:, 1]

end_pred = time.time()

prediction_time = end_pred - start_pred

print(f"Prediction Time: {prediction_time:.6f} seconds")

Prediction Time: 0.026388 seconds

In [58]:
accuracy = accuracy_score(y_test, y_pred_lgbm_opt)
precision = precision_score(y_test, y_pred_lgbm_opt)
recall = recall_score(y_test, y_pred_lgbm_opt)
f1 = f1_score(y_test, y_pred_lgbm_opt)
roc_auc = roc_auc_score(y_test, y_prob_lgbm_opt)

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"ROC-AUC: {roc_auc:.4f}")

Accuracy: 0.9530
Precision: 0.8277
Recall: 0.7880
F1 Score: 0.8074
ROC-AUC: 0.9779

In [59]:
print(classification_report(y_test, y_pred_lgbm_opt))

              precision    recall  f1-score   support

           0       0.97      0.98      0.97      1750
           1       0.83      0.79      0.81       250

    accuracy                           0.95      2000
   macro avg       0.90      0.88      0.89      2000
weighted avg       0.95      0.95      0.95      2000

In [60]:
cm = confusion_matrix(y_test, y_pred_lgbm_opt)
print(cm)

[[1709   41]
 [  53  197]]

In [61]:
optimized_results.append({
    "Model": "Optimized LightGBM",
    "Training Time (s)": training_time,
    "Prediction Time (s)": prediction_time,
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1 Score": f1,
    "ROC-AUC": roc_auc})

## Final Model Comparison and Selection

In [62]:
import pandas as pd

# Baseline model results
results_df = pd.DataFrame(results)

# Optimized model results
optimized_results_df = pd.DataFrame(optimized_results)

In [63]:
print("Baseline Model Performance")
display(results_df)

print("Optimized Model Performance")
display(optimized_results_df)

Baseline Model Performance

,Model,Training Time (s),Prediction Time (s),Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Logistic Regression,0.061730,0.002329,0.9515,0.825532,0.776,0.800000,0.979312
1,XGBoost,0.291051,0.026951,0.9460,0.786290,0.780,0.783133,0.976441
2,LightGBM,0.417768,0.020337,0.9510,0.811475,0.792,0.801619,0.978494

Optimized Model Performance

,Model,Training Time (s),Prediction Time (s),Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Optimized XGBoost,0.243790,0.026451,0.9525,0.818930,0.796,0.807302,0.977689
1,Optimized LightGBM,0.452279,0.026388,0.9530,0.827731,0.788,0.807377,0.977928

In [64]:
print("Baseline Model Performance")
display(results_df)

print("Optimized Model Performance")
display(optimized_results_df)

Baseline Model Performance

,Model,Training Time (s),Prediction Time (s),Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Logistic Regression,0.061730,0.002329,0.9515,0.825532,0.776,0.800000,0.979312
1,XGBoost,0.291051,0.026951,0.9460,0.786290,0.780,0.783133,0.976441
2,LightGBM,0.417768,0.020337,0.9510,0.811475,0.792,0.801619,0.978494

Optimized Model Performance

,Model,Training Time (s),Prediction Time (s),Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Optimized XGBoost,0.243790,0.026451,0.9525,0.818930,0.796,0.807302,0.977689
1,Optimized LightGBM,0.452279,0.026388,0.9530,0.827731,0.788,0.807377,0.977928

In [65]:
# Combine baseline and optimized model results
final_results = pd.concat(
    [results_df, optimized_results_df],
    ignore_index=True
)

# Display the complete comparison table
print("Final Model Comparison")
display(final_results)

Final Model Comparison

,Model,Training Time (s),Prediction Time (s),Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Logistic Regression,0.061730,0.002329,0.9515,0.825532,0.776,0.800000,0.979312
1,XGBoost,0.291051,0.026951,0.9460,0.786290,0.780,0.783133,0.976441
2,LightGBM,0.417768,0.020337,0.9510,0.811475,0.792,0.801619,0.978494
3,Optimized XGBoost,0.243790,0.026451,0.9525,0.818930,0.796,0.807302,0.977689
4,Optimized LightGBM,0.452279,0.026388,0.9530,0.827731,0.788,0.807377,0.977928

In [66]:
# Select the final model
final_model = lgbm_optimized

print("Final Selected Model: Optimized LightGBM")

Final Selected Model: Optimized LightGBM

In [67]:
import joblib

joblib.dump(lgbm_optimized, "final_lightgbm_model.joblib")

['final_lightgbm_model.joblib']

In [72]:
import joblib

feature_names = joblib.load("../Models/model_feature_names.joblib")

print(feature_names)
print(f"\nTotal Features: {len(feature_names)}")

['transaction_amount', 'login_attempts', 'device_risk_score', 'transfer_frequency', 'anomaly_score', 'account_age_days', 'transaction_time_hour', 'failed_transactions_last_30d', 'avg_monthly_balance', 'daily_transaction_count', 'geo_distance_km', 'session_duration_minutes', 'transaction_velocity_score', 'card_present_flag', 'international_transaction_flag', 'suspicious_ip_flag', 'new_account', 'high_value_transaction', 'high_login_attempts', 'high_velocity', 'night_transaction', 'far_distance_transaction', 'high_device_risk', 'payment_channel_Mobile App', 'payment_channel_POS Terminal', 'payment_channel_Web Banking', 'authentication_type_OTP', 'authentication_type_Password Only', 'authentication_type_Two-Factor Authentication']

Total Features: 29

### Model Selection

The baseline and optimized machine learning models were compared using Accuracy, Precision, Recall, F1 Score, ROC-AUC, training time, and prediction time.

Hyperparameter tuning improved the performance of both XGBoost and LightGBM compared to their default configurations.

The Optimized LightGBM model achieved the strongest overall balance between classification performance and computational efficiency, recording the highest Accuracy (95.30%), Precision (82.77%), and F1 Score (80.74%), while maintaining a competitive Recall (78.80%) and ROC-AUC (97.79%).

Based on these results, the Optimized LightGBM model was selected as the final model for the explainable AI fraud detection framework. This model will be used in the subsequent explainability, experiment tracking, and deployment stages of the project.